### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by nthakor** [deathbeds/jupyterlab-fonts#1]
When I hover over font size tab it is not opening. 

![image](https://user-images.githubusercontent.com/19538934/40489768-856dbce8-5f87-11e8-910f-493c764e53ec.png)

**Comment by bollwyvl** [comment]
Thanks for the report!

Are you running with the development environment or with "labextension
install"?

**Comment by nthakor** [comment]
I installed with labextension

**Comment by pwwang** [comment]
Same here.

**Comment by bollwyvl** [comment]
We've done a couple releases since then: closing now, please open a new issue if the problem persists.
