### ISSUE TITLE
install nbjss

### ISSUE THREAD

**Issue by zxdawn** [deathbeds/jupyterlab-fonts#11]
When I `pip install nbjss`, I got this error:
```
Collecting nbjss
  Could not find a version that satisfies the requirement nbjss (from versions: )
No matching distribution found for nbjss
```
jupyter lab version: 0.35.4

**Comment by bollwyvl** [comment]
Yeah, sorry, it's not published on pypi yet!

You can probably (haven't tested) use...

pip install git+https://github.com/deathbeds/jupyterlab-fonts#egginfo=nbjss

...for now, but please remember this is pretty demo-grade code!

**Comment by bollwyvl** [comment]
Also, the python package only provides nbconvert embedding features: the
lab component (which may or may not work with 0.35.*) do not need it.

>

**Comment by zxdawn** [comment]
$ jupyter labextension install \
  @deathbeds/jupyterlab-fonts \
  @deathbeds/jupyterlab-font-anonymous-pro \
  @deathbeds/jupyterlab-font-dejavu-sans-mono \
  @deathbeds/jupyterlab-font-fira-code

```
Node v6.14.4

> /usr/bin/npm pack @deathbeds/jupyterlab-fonts
deathbeds-jupyterlab-fonts-0.5.0.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/application
>=0.19.2 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/notebook
```
It seems doesn't support jupyter lab 0.35.4.

**Comment by bollwyvl** [comment]
Ok, the 0.6.0 line is up and appears to work fine.

I'll see about nbjss soonish!

**Comment by bollwyvl** [comment]
Well, it's looking like nbjss is not going to be coming back... I'm hoping a MIME-based approach will work better for the general case.
