### ISSUE TITLE
Please update bundled fonts

### ISSUE THREAD

**Issue by Zireael** [deathbeds/jupyterlab-fonts#14]
For example, Fira Code v2 has been released.

Also, I'm getting install error:
> This extension does not yet support the current version of JupyterLab.
Latest is: v1.2.1 (October 29, 2019)

Might be worth it that you convert font directories to git submodules - this was people can build with latest fonts included from git if need be.
https://stackoverflow.com/questions/7813030/how-can-i-have-linked-dependencies-in-a-git-repo

**Comment by bollwyvl** [comment]
I haven't had the opportunity or need to update this in a while... Probably
want to get it working with lab 1.0 as well... PRs welcome!

When possible, being able to use npm to manage the the dependencies is
desirable, as there is more predictably to where the fonts will be located
vs. submodules, however.

**Comment by bollwyvl** [comment]
Closed by #16. Thanks for testing jupyterlab-fonts! Please open a new issue if you encounter additional problems.
