### ISSUE TITLE
This extension does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by talentneptuner** [deathbeds/jupyterlab-fonts#15]
Conflicting Dependencies:
JupyterLab              Extension      Package
\>=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/application
\>=1.1.3 <1.2.0          >=0.19.2 <0.20.0@jupyterlab/notebook、

but my version of jupyter bleow

jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
**it looks satisfied**

**Comment by bollwyvl** [comment]
closed by #16

**Comment by bollwyvl** [comment]
Thanks for testing jupyterlab-fonts! Please open a new issue if you encounter additional problems.
