### ISSUE TITLE
Support jupyterlab 2.0+

### ISSUE THREAD

**Issue by PhyX-Meow** [deathbeds/jupyterlab-fonts#17]
Jupyterlab has been updated to 2.0.1, will this extension support the newest version?

**Comment by bollwyvl** [comment]
Thanks for the issue! It will support 2, but I haven't started the work
yet. I'll make sure to bump it in my list!

I'm working through upgrading a couple of the other Deathbeds extension,
but fonts would help other things like outsource be prettier.

 Is there anything in particular you're looking for, other than "does
install"? Is like to get nerd fonts in, and maybe kick the tires on some
additional new fonts.

**Comment by PhyX-Meow** [comment]
Delighted to know the good news, Fira Code is my favorite font, and for me it's just enough. If nerd font is added it will surely be better, though I only need nerd fonts in the terminal.

**Comment by bollwyvl** [comment]
@PhyX-Meow  Sorry for the delay: things got a little... _busy_. It looks like the basics of supporting Lab 2 are out the door, and testing is a little better. Please give it a try, and re-open/create a new issue if you encounter problems.
