### ISSUE TITLE
Core UI "@deathbeds/jupyterlab-fonts" can't install on Jupyter lab 3.0.9

### ISSUE THREAD

**Issue by timesd** [deathbeds/jupyterlab-fonts#27]
Config option `kernel_spec_manager_class` not recognized by `InstallLabExtensionApp`.
[W 2021-02-26 12:24:25.589 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
An error occured.
ValueError: The extension "@deathbeds/jupyterlab-fonts" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.6 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.5 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/mainmenu
>=3.0.6 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/notebook

When can the extension adapt to jupyterlab 3.x?

**Comment by bollwyvl** [comment]
We've already got #26 open for this, so I'm going to close this out. I don't know when I'll have time to upgrade, but do intend to: it's on the broader lab 3 [roadmap](https://github.com/orgs/deathbeds/projects/1). I need to look at why i've marked it as blocked by upstream. 

I'd say PRs welcome, but the DX of working on this repo needs a lot of love... which I have been fixing when doing these upgrades!
