### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by matanster** [deathbeds/jupyterlab-fonts#3]
I can see that this is [going to be merged into Jupyter Lab](https://github.com/jupyterlab/jupyterlab/pull/4673), and I'd like to uninstall, given that the fonts menu brought in by this extension does not show any fonts to choose from when hovered, in my installation. What is the uninstall procedure?

Many thanks, and even more thanks for working on the Jupyter Lab PR of this feature!

**Comment by bollwyvl** [comment]
Sorry I haven't had the time to get this back up and running! Got pretty
far down the notebook line (customizing fonts per notebook) but didn't
quite finish!

You can list extensions with:

jupyter labextension list

And then

jupyter labextension uninstall @deathbeds/jupyterlab-fonts-extension

jupyter labextension uninstall @deathbeds/jupyterlab-font-fira-code

Or whatever sounds like it's related to fonts!

**Comment by bollwyvl** [comment]
Added documentation for [uninstalling](https://github.com/deathbeds/jupyterlab-fonts#uninstalling)!
