### ISSUE TITLE
why your extension can specific an icon

### ISSUE THREAD

**Issue by quantrpeter** [deathbeds/jupyterlab-fonts#67]
Hello, why your extension can specific an icon? 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/50471577/215303716-8f5df6c6-c5bc-4a60-82bf-2ac9a7860534.png">

thanks

**Comment by bollwyvl** [comment]
It's hard coded to the icon of the GitHub user or org that controls the
source repository, as provided in package.json.

https://github.com/jupyterlab/jupyterlab/blob/v3.5.3/packages/extensionmanager/src/widget.tsx#L224

**Comment by quantrpeter** [comment]
thanks a lot

**Comment by quantrpeter** [comment]
sorry, how can you specific your github user name in the project? in order to make it find your avator?
