### ISSUE TITLE
conflict with jupyterlab 4.0

### ISSUE THREAD

**Issue by YubinXie** [deathbeds/jupyterlab-fonts#70]
I upgraded my jupyterlab to 4.0 and when i install jupyterlab font it reinstalls old version of jupyterlab. and when i force install 4.0, font says it requires jupyterlab 3.x and it causes some weird behavior. 

jupyter lab largely improves performance of notebook, and it would be great to check if font can support 4.0.

**Comment by bollwyvl** [comment]
Thanks for checking, but with force installing stuff clearly marked would
break, you get what you pay for from this free software.

Our little band of maintainers will get to it in time, but we're a bit
busy... helping, among other things, get that 4.0 release out earlier this
week. Some patience would be greatly appreciated.

**Comment by bollwyvl** [comment]
This is done.
